<a href="https://colab.research.google.com/github/vishaljoshi24/DungeonsAndDragonsTurnClassification/blob/main/data_preparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

DATA

In [1]:
from datasets import load_dataset
import pandas as pd

In [2]:
dataset = load_dataset("garrykuwanto/crd3_training_pairs", download_mode="force_redownload")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

crd3_training_pairs_no_llm.json: reconstructing file:   0%|          |  0.00B /  773MB

crd3_training_pairs_no_llm.json: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/2360582 [00:00<?, ? examples/s]

In [3]:
df = pd.DataFrame(dataset)

In [4]:
query = []
passage = []
for i in range(len(df.train[0:])):
  query.append(df.train[i]['query'])
  passage.append(df.train[i]['passage'])

df1 = pd.DataFrame({'context': query, 'current turn': passage})

In [5]:
df1

,context,current turn
0,Dialogue context: MATT: And welcome to tonight...,ZAC: Testicular.
1,Dialogue context: ZAC: Fantastical? MATT: Fant...,MATT: It is. It is a testicle episode of Criti...
2,Dialogue context: MATT: Fantastical. ZAC: Test...,ZAC: Cue cut to Ashley!
3,Dialogue context: ZAC: Testicular. MATT: It is...,MATT: Yay! Hi Ashley! She's dancing for it. So...
4,Dialogue context: MATT: It is. It is a testicl...,ZAC: We've got a couple of quick announcements...
...,...,...
2360577,Player says: Not continuing the song... (all l...,"DM responds: Guys, thank you so much for watch..."
2360578,Player says: Not Taliesin.,"DM responds: Not Taliesin, sorry. Liam, Marish..."
2360579,Player says: Saturday.,DM responds: Sorry. Saturday. Friday. It's -
2360580,Player says: It technically is tomorrow.,"DM responds: No, it's not tomorrow yet. Sorry...."
2360581,Player says: Starts tomorrow at 7pm!,DM responds: Thank you. Tomorrow at 7pm. It go...

In [6]:
df2 = df1[(~df1['context'].str.startswith('Scene context:')) & (~df1['context'].str.startswith('Player says:'))]
# (~df1['current turn'].str.startswith('MATT:'))
# (~df1['current turn'].str.startswith('DM Responds:'))
# (~df1['current turn'].str.startswith('MATT Responds:')) &

In [7]:
df2

,context,current turn
0,Dialogue context: MATT: And welcome to tonight...,ZAC: Testicular.
1,Dialogue context: ZAC: Fantastical? MATT: Fant...,MATT: It is. It is a testicle episode of Criti...
2,Dialogue context: MATT: Fantastical. ZAC: Test...,ZAC: Cue cut to Ashley!
3,Dialogue context: ZAC: Testicular. MATT: It is...,MATT: Yay! Hi Ashley! She's dancing for it. So...
4,Dialogue context: MATT: It is. It is a testicl...,ZAC: We've got a couple of quick announcements...
...,...,...
2356317,ALL says: Saturday.,MATT responds: Sorry. Saturday. Friday. It's -
2356318,MATT says: Sorry. Saturday. Friday. It's -,TALIESIN responds: It technically is tomorrow.
2356319,TALIESIN says: It technically is tomorrow.,"MATT responds: No, it's not tomorrow yet. Sorr..."
2356320,"MATT says: No, it's not tomorrow yet. Sorry. S...",LUCAS responds: Starts tomorrow at 7pm!
2356321,LUCAS says: Starts tomorrow at 7pm!,MATT responds: Thank you. Tomorrow at 7pm. It ...

In [8]:
df3 = df2[(~df2['current turn'].str.startswith('AUDIENCE:'))]

In [9]:
df3

,context,current turn
0,Dialogue context: MATT: And welcome to tonight...,ZAC: Testicular.
1,Dialogue context: ZAC: Fantastical? MATT: Fant...,MATT: It is. It is a testicle episode of Criti...
2,Dialogue context: MATT: Fantastical. ZAC: Test...,ZAC: Cue cut to Ashley!
3,Dialogue context: ZAC: Testicular. MATT: It is...,MATT: Yay! Hi Ashley! She's dancing for it. So...
4,Dialogue context: MATT: It is. It is a testicl...,ZAC: We've got a couple of quick announcements...
...,...,...
2356317,ALL says: Saturday.,MATT responds: Sorry. Saturday. Friday. It's -
2356318,MATT says: Sorry. Saturday. Friday. It's -,TALIESIN responds: It technically is tomorrow.
2356319,TALIESIN says: It technically is tomorrow.,"MATT responds: No, it's not tomorrow yet. Sorr..."
2356320,"MATT says: No, it's not tomorrow yet. Sorry. S...",LUCAS responds: Starts tomorrow at 7pm!
2356321,LUCAS says: Starts tomorrow at 7pm!,MATT responds: Thank you. Tomorrow at 7pm. It ...

In [10]:
df4 = df3.drop_duplicates(subset=['context'], inplace=False)

In [11]:
df4

,context,current turn
0,Dialogue context: MATT: And welcome to tonight...,ZAC: Testicular.
1,Dialogue context: ZAC: Fantastical? MATT: Fant...,MATT: It is. It is a testicle episode of Criti...
2,Dialogue context: MATT: Fantastical. ZAC: Test...,ZAC: Cue cut to Ashley!
3,Dialogue context: ZAC: Testicular. MATT: It is...,MATT: Yay! Hi Ashley! She's dancing for it. So...
4,Dialogue context: MATT: It is. It is a testicl...,ZAC: We've got a couple of quick announcements...
...,...,...
2344063,"Dialogue context: LIAM: Ja, but I rolled an 18...",SAM: I'll just run over to Jester and give her...
2344065,Dialogue context: SAM: I'll just run over to J...,MARISHA: They're all unconscious?
2344068,Dialogue context: MARISHA: They're all unconsc...,KHARY: It will be. It's absolutely better than...
2352766,Dialogue context: TRAVIS: Who's with the burnt...,LAURA: Big tavern brawl!
2353049,Dialogue context: in unison MARISHA TALIESIN: ...,MATT: Sorry. Saturday. Friday. It's -

In [12]:
df5 = df4.drop_duplicates(subset=['current turn'], inplace=False)

In [13]:
df5

,context,current turn
0,Dialogue context: MATT: And welcome to tonight...,ZAC: Testicular.
1,Dialogue context: ZAC: Fantastical? MATT: Fant...,MATT: It is. It is a testicle episode of Criti...
2,Dialogue context: MATT: Fantastical. ZAC: Test...,ZAC: Cue cut to Ashley!
3,Dialogue context: ZAC: Testicular. MATT: It is...,MATT: Yay! Hi Ashley! She's dancing for it. So...
4,Dialogue context: MATT: It is. It is a testicl...,ZAC: We've got a couple of quick announcements...
...,...,...
2259502,MATT says: Gathering up the rest of those who ...,ASHLEY responds: Sex. It's sex. It's lots of s...
2259503,ASHLEY says: Sex. It's sex. It's lots of sex. ...,"MATT responds: All right. Well then, we're goi..."
2259504,"MATT says: All right. Well then, we're going t...","KHARY responds: You know what, hold on! Take a..."
2259505,"KHARY says: You know what, hold on! Take a bow...",MATT responds: Thank you all so very much for ...
2329854,"Dialogue context: MATT: Hello everyone, welcom...",MATT: That I get to open.

In [14]:
df6 = df5[70:] #Point at which gameplay starts

In [15]:
df6

,context,current turn
71,Dialogue context: ASHLEY: Yeah! MATT: By the w...,ASHLEY: I know! I didn't even mean-- I just pu...
72,"Dialogue context: MATT: By the way, thank you ...","TRAVIS: Mass panic, it's no big deal."
73,Dialogue context: in unison SAM MATT: Includin...,MATT: You're technically still here. And you k...
74,Dialogue context: ASHLEY: I know! I didn't eve...,ASHLEY: Really? (laughs)
75,"Dialogue context: TRAVIS: Mass panic, it's no ...","TRAVIS: Hello, Pike!"
...,...,...
2259502,MATT says: Gathering up the rest of those who ...,ASHLEY responds: Sex. It's sex. It's lots of s...
2259503,ASHLEY says: Sex. It's sex. It's lots of sex. ...,"MATT responds: All right. Well then, we're goi..."
2259504,"MATT says: All right. Well then, we're going t...","KHARY responds: You know what, hold on! Take a..."
2259505,"KHARY says: You know what, hold on! Take a bow...",MATT responds: Thank you all so very much for ...
2329854,"Dialogue context: MATT: Hello everyone, welcom...",MATT: That I get to open.

In [16]:
df6.to_json('cleaned_data.json', orient='split', compression='infer', index=True)

In [17]:
cleaned_data = pd.read_json('cleaned_data.json', orient='split', compression='infer')

In [18]:
cleaned_data

,context,current turn
71,Dialogue context: ASHLEY: Yeah! MATT: By the w...,ASHLEY: I know! I didn't even mean-- I just pu...
72,"Dialogue context: MATT: By the way, thank you ...","TRAVIS: Mass panic, it's no big deal."
73,Dialogue context: in unison SAM MATT: Includin...,MATT: You're technically still here. And you k...
74,Dialogue context: ASHLEY: I know! I didn't eve...,ASHLEY: Really? (laughs)
75,"Dialogue context: TRAVIS: Mass panic, it's no ...","TRAVIS: Hello, Pike!"
...,...,...
2259502,MATT says: Gathering up the rest of those who ...,ASHLEY responds: Sex. It's sex. It's lots of s...
2259503,ASHLEY says: Sex. It's sex. It's lots of sex. ...,"MATT responds: All right. Well then, we're goi..."
2259504,"MATT says: All right. Well then, we're going t...","KHARY responds: You know what, hold on! Take a..."
2259505,"KHARY says: You know what, hold on! Take a bow...",MATT responds: Thank you all so very much for ...
2329854,"Dialogue context: MATT: Hello everyone, welcom...",MATT: That I get to open.

In [19]:
# unlabelled_trainset_draft = df1[113:513]

# filename = 'unlabelled_trainset_draft.xlsx'
# unlabelled_trainset_draft.to_excel(filename)

In [20]:
cleaned_data[284:]

,context,current turn
382,"Dialogue context: LAURA: Except for you, darli...",MATT: Yeah. This giant rotund Percy on his han...
383,Dialogue context: MATT: It's very weird. You'r...,LAURA: That is awkward.
384,Dialogue context: TALIESIN: Bear-Percy is espe...,"MATT: It's a very strange visual, and you're v..."
385,Dialogue context: MATT: Yeah. This giant rotun...,ASHLEY: I give Percy-Trink some ear scratches.
386,Dialogue context: LAURA: That is awkward. MATT...,LAURA: He likes it.
...,...,...
2259502,MATT says: Gathering up the rest of those who ...,ASHLEY responds: Sex. It's sex. It's lots of s...
2259503,ASHLEY says: Sex. It's sex. It's lots of sex. ...,"MATT responds: All right. Well then, we're goi..."
2259504,"MATT says: All right. Well then, we're going t...","KHARY responds: You know what, hold on! Take a..."
2259505,"KHARY says: You know what, hold on! Take a bow...",MATT responds: Thank you all so very much for ...
2329854,"Dialogue context: MATT: Hello everyone, welcom...",MATT: That I get to open.

In [22]:
cleaned_data[1939:2339]

,context,current turn
2176,"Dialogue context: ASHLEY: 26. MATT: 26, all ri...",MATT: 5th-level Healing Word. All righty. That...
2177,"Dialogue context: MATT: 26, all right. What le...",SAM: Do it!
2178,"Dialogue context: ASHLEY: Five. Sorry, I did f...","ASHLEY: Shoot. Okay, I'm not close to him."
2179,Dialogue context: MATT: 5th-level Healing Word...,LIAM: Can you unleash some holy fire on any fu...
2180,Dialogue context: SAM: Do it! ASHLEY: Shoot. O...,LAURA: Yeah! Like a radiant blast or something?
...,...,...
2626,Dialogue context: MARISHA: Can I go for a trip...,MATT: Okay! Roll damage.
2627,"Dialogue context: MATT: No, this is just a mel...",LIAM: We've got the MVP over here.
2628,"Dialogue context: MARISHA: Fine, I'm going to ...",MARISHA: 12 damage! Bam!
2629,Dialogue context: MATT: Okay! Roll damage. LIA...,MATT: Crack! You hit her in the back of the he...
2630,Dialogue context: LIAM: We've got the MVP over...,SAM: Can I Counterspell that?

In [23]:
train_set = cleaned_data[1939:2339]

In [24]:
filename = 'refined_collaboration_codes.xlsx'
train_set.to_excel(filename)