<a href="https://colab.research.google.com/github/vishaljoshi24/DungeonsAndDragonsTurnClassification/blob/main/turn_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone 'https://github.com/vishaljoshi24/Dungeons-and-Dragons-Turn-Classification/'

Cloning into 'Dungeons-and-Dragons-Turn-Classification'...
remote: Enumerating objects: 548, done.
remote: Counting objects: 100% (200/200), done.
remote: Compressing objects: 100% (136/136), done.
remote: Total 548 (delta 135), reused 76 (delta 64), pack-reused 348 (from 2)
Receiving objects: 100% (548/548), 3.14 MiB | 17.59 MiB/s, done.
Resolving deltas: 100% (315/315), done.

In [2]:
# !pip install dspy==3.1.0
!pip install dspy

Collecting dspy
  Downloading dspy-3.2.1-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: openai>=0.28.1 in /usr/local/lib/python3.12/dist-packages (from dspy) (2.43.0)
Requirement already satisfied: regex>=2023.10.3 in /usr/local/lib/python3.12/dist-packages (from dspy) (2025.11.3)
Requirement already satisfied: orjson>=3.9.0 in /usr/local/lib/python3.12/dist-packages (from dspy) (3.11.9)
Requirement already satisfied: tqdm>=4.66.1 in /usr/local/lib/python3.12/dist-packages (from dspy) (4.67.3)
Requirement already satisfied: requests>=2.31.0 in /usr/local/lib/python3.12/dist-packages (from dspy) (2.32.4)
Requirement already satisfied: pydantic>=2.0 in /usr/local/lib/python3.12/dist-packages (from dspy) (2.13.4)
Collecting litellm>=1.64.0 (from dspy)
  Downloading litellm-1.92.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.0/41.0 kB 2.6 MB/s eta 0:00:00
Collecting diskcache>=5.6.0 (from dspy)
  Downloading diskcache-5.6.3-py3-none-any.whl.metadata (20 kB)
Collecting json-repair>=0.54.2 (from dspy)
  Downloading json_repair-0.61.4-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: tenacity>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from dspy) (9.1.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from dspy) (4.14.0)
Collecting asyncer==0.0.8 (from dspy)
  Downloading asyncer-0.0.8-py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: cachetools>=5.5.0 in /usr/local/lib/python3.12/dist-packages (from dspy) (6.2.6)
Requirement already satisfied: cloudpickle>=3.1.2 in /usr/local/lib/python3.12/dist-packages (from dspy) (3.1.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from dspy) (2.0.2)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from dspy) (3.7.1)
Collecting gepa==0.0.27 (from gepa[dspy]==0.0.27->dspy)
  Downloading gepa-0.0.27-py3-none-any.whl.metadata (30 kB)
Collecting typeguard==4.4.3 (from dspy)
  Downloading typeguard-4.4.3-py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: typing_extensions>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from typeguard==4.4.3->dspy) (4.15.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio->dspy) (3.18)
Collecting fastuuid<1.0,>=0.14.0 (from litellm>=1.64.0->dspy)
  Downloading fastuuid-0.14.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.1 kB)
Requirement already satisfied: httpx<1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from litellm>=1.64.0->dspy) (0.28.1)
Requirement already satisfied: python-dotenv<2.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from litellm>=1.64.0->dspy) (1.2.2)
Requirement already satisfied: tiktoken<1.0,>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from litellm>=1.64.0->dspy) (0.13.0)
Collecting importlib-metadata<9.0,>=8.0.0 (from litellm>=1.64.0->dspy)
  Downloading importlib_metadata-8.9.0-py3-none-any.whl.metadata (4.5 kB)
Requirement already satisfied: tokenizers<1.0,>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from litellm>=1.64.0->dspy) (0.22.2)
Requirement already satisfied: click<9.0,>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from litellm>=1.64.0->dspy) (8.4.2)
Requirement already satisfied: jinja2<4.0,>=3.1.6 in /usr/local/lib/python3.12/dist-packages (from litellm>=1.64.0->dspy) (3.1.6)
Requirement already satisfied: aiohttp<4.0,>=3.10 in /usr/local/lib/python3.12/dist-packages (from litellm>=1.64.0->dspy) (3.14.1)
Requirement already satisfied: jsonschema<5.0,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from litellm>=1.64.0->dspy) (4.26.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai>=0.28.1->dspy) (1.9.0)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai>=0.28.1->dspy) (0.15.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai>=0.28.1->dspy) (1.3.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->dspy) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->dspy) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->dspy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31.0->dspy) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31.0->dspy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31.0->dspy) (2026.6.17)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0,>=3.10->litellm>=1.64.0->dspy) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0,>=3.10->litellm>=1.64.0->dspy) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0,>=3.10->litellm>=1.64.0->dspy) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0,>=3.10->litellm>=1.64.0->dspy) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0,>=3.10->litellm>=1.64.0->dspy) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0,>=3.10->litellm>=1.64.0->dspy) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0,>=3.10->litellm>=1.64.0->dspy) (1.24.2)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0,>=0.28.0->litellm>=1.64.0->dspy) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0,>=0.28.0->litellm>=1.64.0->dspy) (0.16.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata<9.0,>=8.0.0->litellm>=1.64.0->dspy) (4.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<4.0,>=3.1.6->litellm>=1.64.0->dspy) (3.0.3)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema<5.0,>=4.0.0->litellm>=1.64.0->dspy) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema<5.0,>=4.0.0->litellm>=1.64.0->dspy) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema<5.0,>=4.0.0->litellm>=1.64.0->dspy) (2026.5.1)
Requirement already satisfied: huggingface-hub<2.0,>=0.16.4 in /usr/local/lib/python3.12/dist-packages (from tokenizers<1.0,>=0.21.0->litellm>=1.64.0->dspy) (1.20.1)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers<1.0,>=0.21.0->litellm>=1.64.0->dspy) (3.29.4)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers<1.0,>=0.21.0->litellm>=1.64.0->dspy) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers<1.0,>=0.21.0->litellm>=1.64.0->dspy) (1.5.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers<1.0,>=0.21.0->litellm>=1.64.0->dspy) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers<1.0,>=0.21.0->litellm>=1.64.0->dspy) (6.0.3)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers<1.0,>=0.21.0->litellm>=1.64.0->dspy) (0.25.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.16.4->tokenizers<1.0,>=0.21.0->litellm>=1.64.0->dspy) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.16.4->tokenizers<1.0,>=0.21.0->litellm>=1.64.0->dspy) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.16.4->tokenizers<1.0,>=0.21.0->litellm>=1.64.0->dspy) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.16.4->tokenizers<1.0,>=0.21.0->litellm>=1.64.0->dspy) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.16.4->tokenizers<1.0,>=0.21.0->litellm>=1.64.0->dspy) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.16.4->tokenizers<1.0,>=0.21.0->litellm>=1.64.0->dspy) (0.1.2)
Downloading dspy-3.2.1-py3-none-any.whl (331 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.0/331.0 kB 9.0 MB/s eta 0:00:00
Downloading asyncer-0.0.8-py3-none-any.whl (9.2 kB)
Downloading gepa-0.0.27-py3-none-any.whl (146 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 146.5/146.5 kB 14.8 MB/s eta 0:00:00
Downloading typeguard-4.4.3-py3-none-any.whl (34 kB)
Downloading diskcache-5.6.3-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 kB 4.2 MB/s eta 0:00:00
Downloading json_repair-0.61.4-py3-none-any.whl (49 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.6/49.6 kB 4.3 MB/s eta 0:00:00
Downloading litellm-1.92.0-cp312-cp312-manylinux_2_28_x86_64.whl (19.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.3/19.3 MB 110.7 MB/s eta 0:00:00
Downloading fastuuid-0.14.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (278 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 278.1/278.1 kB 23.2 MB/s eta 0:00:00
Downloading importlib_metadata-8.9.0-py3-none-any.whl (27 kB)
Installing collected packages: typeguard, json-repair, importlib-metadata, gepa, fastuuid, diskcache, asyncer, litellm, dspy
  Attempting uninstall: typeguard
    Found existing installation: typeguard 4.5.2
    Uninstalling typeguard-4.5.2:
      Successfully uninstalled typeguard-4.5.2
  Attempting uninstall: importlib-metadata
    Found existing installation: importlib_metadata 9.0.0
    Uninstalling importlib_metadata-9.0.0:
      Successfully uninstalled importlib_metadata-9.0.0
Successfully installed asyncer-0.0.8 diskcache-5.6.3 dspy-3.2.1 fastuuid-0.14.0 gepa-0.0.27 importlib-metadata-8.9.0 json-repair-0.61.4 litellm-1.92.0 typeguard-4.4.3

In [3]:
import pandas as pd
import dspy

# Data

In [4]:
training_df = pd.read_excel('Dungeons-and-Dragons-Turn-Classification/pipeline_testing_set.xlsx')

In [5]:
training_df

,Index,context,current turn,category,Unnamed: 4
0,433,Dialogue context: MATT: This is a survival. LA...,LAURA: That's where the acid pits are. Acid. B...,Worldbuilding,NaN
1,435,"Dialogue context: MATT: 16, okay. You get down...","MATT: All right. Continuing to push forward, a...",Worldbuilding,NaN
2,436,Dialogue context: LAURA: That's where the acid...,LIAM: Looks a little hinky?,Worldbuilding,NaN
3,437,Dialogue context: TRAVIS: Yeah. MATT: All righ...,"MATT: It looks like it's deliberately placed, ...",Worldbuilding,NaN
4,438,Dialogue context: MATT: All right. Continuing ...,LIAM: I'd like to carefully approach and disar...,Strategising,NaN
...,...,...,...,...,...
395,857,Dialogue context: MATT: Okay. The bullet slams...,TRAVIS: What about these jewels?,Worldbuilding,NaN
396,858,Dialogue context: LIAM: I have advantage. MATT...,MATT: The Feast gives you advantage.,Gameplay Mechanic,NaN
397,859,Dialogue context: MATT: You do. TRAVIS: What a...,"LIAM: The Feast gives me advantage, well, but ...",Gameplay Mechanic,NaN
398,860,Dialogue context: TRAVIS: What about these jew...,MATT: You rolled a 16? All right.,Gameplay Mechanic,NaN
399,861,Dialogue context: MATT: The Feast gives you ad...,TALIESIN: It was a good thought.,Out-Of-Game Conversation,NaN

In [6]:
training_df.drop(columns=['Index'], inplace=True)

In [7]:
training_df.drop(columns=['Unnamed: 4'], inplace=True)

In [8]:
training_df

,context,current turn,category
0,Dialogue context: MATT: This is a survival. LA...,LAURA: That's where the acid pits are. Acid. B...,Worldbuilding
1,"Dialogue context: MATT: 16, okay. You get down...","MATT: All right. Continuing to push forward, a...",Worldbuilding
2,Dialogue context: LAURA: That's where the acid...,LIAM: Looks a little hinky?,Worldbuilding
3,Dialogue context: TRAVIS: Yeah. MATT: All righ...,"MATT: It looks like it's deliberately placed, ...",Worldbuilding
4,Dialogue context: MATT: All right. Continuing ...,LIAM: I'd like to carefully approach and disar...,Strategising
...,...,...,...
395,Dialogue context: MATT: Okay. The bullet slams...,TRAVIS: What about these jewels?,Worldbuilding
396,Dialogue context: LIAM: I have advantage. MATT...,MATT: The Feast gives you advantage.,Gameplay Mechanic
397,Dialogue context: MATT: You do. TRAVIS: What a...,"LIAM: The Feast gives me advantage, well, but ...",Gameplay Mechanic
398,Dialogue context: TRAVIS: What about these jew...,MATT: You rolled a 16? All right.,Gameplay Mechanic
399,Dialogue context: MATT: The Feast gives you ad...,TALIESIN: It was a good thought.,Out-Of-Game Conversation

In [9]:
trainset = []

for context, current_turn, category in training_df.values:
    examples = dspy.Example(context=context, question=current_turn, response=category).with_inputs("context", "question")
    trainset.append(examples)

In [10]:
trainset[:5]

[Example({'context': "Dialogue context: MATT: This is a survival. LAURA: Oh. Well, it's the same. That is a 16. MATT: 16, okay. You get down and inspect the area. You actually pull out a small bit of torch pith and light it a bit just to get a little light across this one intersection briefly. There are footprints back and forth in all ways, but many of them have been, at least the footprints coming from, and the last footprints were coming from this tunnel to your immediate left, were from a while back. The fresher footprints, fresh as of four hours, continue on down that way. You do notice that the smell of the air itself is, you notice this as well as you're inspecting, the air down here has a very acrid, sharp scent anyway, a hint of chemical. It seems to be getting stronger to the left.", 'question': "LAURA: That's where the acid pits are. Acid. Briarwoods. Briarwoods?", 'response': 'Worldbuilding'}) (input_keys={'context', 'question'}),
 Example({'context': "Dialogue context: MATT: 16, okay. You get down and inspect the area. You actually pull out a small bit of torch pith and light it a bit just to get a little light across this one intersection briefly. There are footprints back and forth in all ways, but many of them have been, at least the footprints coming from, and the last footprints were coming from this tunnel to your immediate left, were from a while back. The fresher footprints, fresh as of four hours, continue on down that way. You do notice that the smell of the air itself is, you notice this as well as you're inspecting, the air down here has a very acrid, sharp scent anyway, a hint of chemical. It seems to be getting stronger to the left. LAURA: That's where the acid pits are. Acid. Briarwoods. Briarwoods? TRAVIS: Yeah.", 'question': "MATT: All right. Continuing to push forward, about another five minutes or so, keeping track of your distance to the castle you're starting to get towards the outside perimeter of the actual city itself. As you're keeping tabs on distance traveled to that area, you catch, based on your last perception roll, there is a portion of the floor that seems to have some placed crooked chunks of stone. You see pieces of broken stone here and there, things that have fallen out from being hauled from the distant dig into wherever the ziggurat is, but there's one section where it appears there's platforms.", 'response': 'Worldbuilding'}) (input_keys={'context', 'question'}),
 Example({'context': "Dialogue context: LAURA: That's where the acid pits are. Acid. Briarwoods. Briarwoods? TRAVIS: Yeah. MATT: All right. Continuing to push forward, about another five minutes or so, keeping track of your distance to the castle you're starting to get towards the outside perimeter of the actual city itself. As you're keeping tabs on distance traveled to that area, you catch, based on your last perception roll, there is a portion of the floor that seems to have some placed crooked chunks of stone. You see pieces of broken stone here and there, things that have fallen out from being hauled from the distant dig into wherever the ziggurat is, but there's one section where it appears there's platforms.", 'question': 'LIAM: Looks a little hinky?', 'response': 'Worldbuilding'}) (input_keys={'context', 'question'}),
 Example({'context': "Dialogue context: TRAVIS: Yeah. MATT: All right. Continuing to push forward, about another five minutes or so, keeping track of your distance to the castle you're starting to get towards the outside perimeter of the actual city itself. As you're keeping tabs on distance traveled to that area, you catch, based on your last perception roll, there is a portion of the floor that seems to have some placed crooked chunks of stone. You see pieces of broken stone here and there, things that have fallen out from being hauled from the distant dig into wherever the ziggurat is, but there's one section where it appears there's platforms. LIAM: Looks a little hinky?", 'question': "MATT: It looks like it's deliberately placed, as opposed to dropped and left there.", 'response': 'Worldbuilding'}) (input_keys={'context', 'question'}),
 Example({'context': "Dialogue context: MATT: All right. Continuing to push forward, about another five minutes or so, keeping track of your distance to the castle you're starting to get towards the outside perimeter of the actual city itself. As you're keeping tabs on distance traveled to that area, you catch, based on your last perception roll, there is a portion of the floor that seems to have some placed crooked chunks of stone. You see pieces of broken stone here and there, things that have fallen out from being hauled from the distant dig into wherever the ziggurat is, but there's one section where it appears there's platforms. LIAM: Looks a little hinky? MATT: It looks like it's deliberately placed, as opposed to dropped and left there.", 'question': "LIAM: I'd like to carefully approach and disarm anything I can detect or find.", 'response': 'Strategising'}) (input_keys={'context', 'question'})]

# Language Model

In [11]:
lm = dspy.LM('ollama_chat/qwen3:8b', api_base = 'http://localhost:11434', api_key='', max_tokens=2048)
dspy.configure(lm=lm)

# Signatures

In [12]:
from typing import Literal


class TurnClassifier(dspy.Signature):
    """Given the context for a Dungeons & Dragons game turn and the game turn itself, classify the turn."""
    context: str = dspy.InputField(desc = "The three previous game turns which describe a player's action or their dialogue.")
    question: str = dspy.InputField (desc="The current turn taken by a player, which can include a description of an action or a piece of dialogue.")
    response: Literal['Gameplay Mechanic',
                      'Out-Of-Game Conversation',
                      'Worldbuilding',
                      'Strategising',
                      ] = dspy.OutputField()

class PlayerInstruction(dspy.Signature):
  category: Literal['Gameplay Mechanic',
                    'Out-Of-Game Conversation',
                    'Worldbuilding',
                    'Strategising',
                    ] = dspy.InputField()
  player_instruction:str = dspy.OutputField(desc="instruction on how to behave within a D&D game.")

# Modules

In [13]:
class ClassifyTurns(dspy.Module):
  def __init__(self):
    self.classifier = dspy.ChainOfThought(TurnClassifier, caching=False)

  def forward(self, context, question, **kwargs):
    prediction = self.classifier(context=context, question=question)
    return prediction

In [14]:
classify = ClassifyTurns()
def classify_turn(context, question):
    try:
        predicted_category = classify(context=context, question=question)
        return predicted_category
    except Exception as e:
        return 0

In [15]:
# class PromptGenerator(dspy.Module):
#   def __init__(self):
#     self.classifier = classify
#     self.generator = dspy.ChainOfThought(PlayerInstruction, caching=False)

#   def forward(self, context, question, **kwargs):
#     pred_category = classify(context=context, question=question)
#     prompt = self.generator(category=pred_category)
#     return prompt, pred_category

# prompt_generator = PromptGenerator()

In [16]:
# prompt_generator(trainset[1]['context'], trainset[1]['question'])

In [17]:
predicted_categories = []

for i in range(len(trainset[0:50])):
    predicted_categories.append(classify_turn(trainset[i]['context'], trainset[i]['question']))

In [18]:
true_categories = []

for i in range(len(trainset[0:50])):
  true_categories.append(trainset[i]['response'])

In [19]:
predicted_categories

[Prediction(
     reasoning="Laura's response provides additional information about the environment, specifically referencing the acid pits and Briarwoods, which are part of the game world's details. This contributes to the understanding of the setting and its hazards, aligning with worldbuilding.",
     response='Worldbuilding'
 ),
 Prediction(
     reasoning='The current turn involves Matt describing the environmental details the group encounters as they move through the area, including observations about the terrain, broken stones, and platforms. This contributes to the narrative and setting of the game world, providing players with sensory and spatial information to enhance immersion and understanding of the environment.',
     response='Worldbuilding'
 ),
 Prediction(
     reasoning='Liam\'s comment is an in-character observation about the environment, noting something suspicious ("hinky") that aligns with the group\'s exploration of the dungeon\'s layout. This reflects the players\' interaction with the game world\'s details, contributing to the narrative and potential puzzle-solving.',
     response='Worldbuilding'
 ),
 Prediction(
     reasoning="The response describes the deliberate placement of stones in the environment, contributing to the narrative and setting details of the game world. This is part of the story's worldbuilding, explaining the environment's features and their significance within the game's context.",
     response='Worldbuilding'
 ),
 Prediction(
     reasoning="Liam's statement represents a player's intention to interact with the environment by searching for and disarming potential hazards, which is a standard gameplay mechanic in tabletop RPGs involving skill checks, trap detection, and environmental interaction.",
     response='Gameplay Mechanic'
 ),
 Prediction(
     reasoning="Matt's response prompts Liam to perform a specific in-game action (making a check), which is a direct gameplay mechanic interaction. This aligns with the game's rules for resolving actions and checks.",
     response='Gameplay Mechanic'
 ),
 Prediction(
     reasoning="The question involves Liam inquiring about the nature of an object (thieves' tools) within the game's narrative. This pertains to understanding the game's elements and their role in the world, which falls under worldbuilding. The dialogue is part of the in-game exploration and interaction with the environment, not a meta-discussion or strategic planning.",
     response='Worldbuilding'
 ),
 Prediction(
     reasoning="The response confirms the identification of thieves' tools, which is directly related to the mechanics of skill checks and item usage within the game. This interaction facilitates gameplay by resolving ambiguity about an item's purpose.",
     response='Gameplay Mechanic'
 ),
 Prediction(
     reasoning='Liam\'s statement of "That\'s a 27" directly relates to the outcome of a die roll associated with using thieves\' tools, which is a core gameplay mechanic in D&D. This reflects the result of a check that impacts the game\'s progression.',
     response='Gameplay Mechanic'
 ),
 Prediction(
     reasoning="The current turn describes Matt narrating a scenario within the game world, detailing environmental hazards (the magical burst under stone slabs) and the party's interaction with it. This involves setting the scene and explaining the game's environment, which falls under worldbuilding. While there are mechanical elements (marking, wedging), the primary function here is to establish the world's context for the players.",
     response='Worldbuilding'
 ),
 Prediction(
     reasoning="Liam's statement is a direct in-game communication about marked stones that pose a hazard, which aligns with the previous context of managing magical traps and preventing triggers. This is part of the active gameplay interaction rather than out-of-game discussion or worldbuilding.",
     response='Gameplay Mechanic'
 ),
 Prediction(
     reasoning='TALIESIN\'s response "Copy" is a simple acknowledgment of the previous instruction without introducing new gameplay elements, dialogue, or strategic considerations. It serves as a standard out-of-game confirmation rather than advancing the narrative or mechanics.',
     response='Out-Of-Game Conversation'
 ),
 Prediction(
     reasoning='TRAVIS\'s instruction to "Somebody tell Trinket" indicates an in-game communication directive, likely informing another player character (Trinket) about the hazardous stones. This aligns with the prior context of avoiding magical traps and represents a gameplay mechanic involving character interaction and situational awareness.',
     response='Gameplay Mechanic'
 ),
 Prediction(
     reasoning="The dialogue involves characters referencing names (Trinket, Pike) within the game's narrative, which adds to the fictional world's character roster. This is part of establishing the game's fictional elements and relationships between characters.",
     response='Worldbuilding'
 ),
 Prediction(
     reasoning="The dialogue involves characters discussing a character's ability to understand signs, which relates to in-game mechanics or character capabilities. Since the context includes previous interactions about communication and instructions, Laura's statement likely pertains to gameplay mechanics or character abilities within the game world.",
     response='Gameplay Mechanic'
 ),
 Prediction(
     reasoning="Marisha's statement about guiding Trinket directly addresses a strategic role assignment within the game's narrative, indicating a decision about character responsibilities during the adventure. This aligns with planning and coordinating actions within the game context.",
     response='Strategising'
 ),
 Prediction(
     reasoning='The dialogue involves characters discussing their abilities and interactions within the game world. Laura\'s statement about "He listens to you" pertains to the character\'s traits or mechanics, which are part of the gameplay dynamics. The conversation remains in-character and focuses on the game\'s narrative and rules rather than out-of-game topics or worldbuilding.',
     response='Gameplay Mechanic'
 ),
 Prediction(
     reasoning='The line "The awkward large bear-Percy--" appears to be a narrative or descriptive comment within the game\'s story, possibly referencing a character (Percy) or a creature (the bear). Since it does not directly relate to gameplay mechanics, strategizing, or out-of-game discussion, it contributes to the worldbuilding by hinting at elements of the game\'s setting or characters.',
     response='Worldbuilding'
 ),
 Prediction(
     reasoning="The dialogue appears to be part of the game's narrative, where players are discussing in-game events or character interactions. The mention of a message being received suggests it's contributing to the world's storyline or character dynamics, which falls under worldbuilding.",
     response='Worldbuilding'
 ),
 Prediction(
     reasoning="The dialogue revolves around in-game character relationships and emotional dynamics, specifically addressing the bond between Marisha's character and the bear-Percy. This reflects the narrative and emotional framework of the story world, establishing character connections and their significance within the game's context.",
     response='Worldbuilding'
 ),
 Prediction(
     reasoning="The current turn involves the game master (MATT) prompting the players to perform a perception check as part of the game's mechanical process. This directly relates to the gameplay mechanics of the Dungeons & Dragons system, where checks are used to resolve actions and interactions within the game world.",
     response='Gameplay Mechanic'
 ),
 Prediction(
     reasoning='Liam\'s response of "20" is likely indicating the result of a d20 roll for a perception check, as Matt previously instructed the group to make one. This directly relates to the gameplay mechanic of resolving ability checks in Dungeons & Dragons.',
     response='Gameplay Mechanic'
 ),
 Prediction(
     reasoning="Laura's action of rolling a perception check (21) is a direct continuation of the gameplay mechanic initiated by Matt's instruction. This involves resolving a game task through dice rolls, which is a core aspect of Dungeons & Dragons mechanics.",
     response='Gameplay Mechanic'
 ),
 Prediction(
     reasoning="The response describes the game's environment, the trap mechanism, and the immediate consequences of the players' actions. Matt is narrating the world's reaction to their movement, emphasizing the environment's details (dirt mound, lack of dust) and the trap's setup. This is part of the game's immersive worldbuilding rather than a gameplay rule, out-of-game chat, or strategy discussion.",
     response='Worldbuilding'
 ),
 Prediction(
     reasoning='Liam\'s statement involves his character\'s action of using a rogue\'s movement ability to reposition, followed by an ability check (26). This directly relates to the mechanics of navigating traps and resolving checks within the game, aligning with the previous trap interaction. The "universal rogue movement" and the numeric result are explicit gameplay mechanics.',
     response='Gameplay Mechanic'
 ),
 Prediction(
     reasoning="The response details the mechanical interaction with a trap, explaining how the players' actions trigger a reaction (shifting dirt, gas containment) and the implications for disarming it. This directly relates to the rules and mechanics of the game world, specifically trap interaction and environmental hazards.",
     response='Gameplay Mechanic'
 ),
 Prediction(
     reasoning="Liam's question is seeking clarification on the trap's scope to inform strategic decisions about navigating the passage. This involves assessing risks and planning next steps based on the trap's mechanics, which falls under strategising.",
     response='Strategising'
 ),
 Prediction(
     reasoning="The response details the mechanics of bypassing a trap, explains the trap's positioning, and introduces a difficulty check for interacting with a trinket. This directly relates to the rules and mechanics of navigating environmental hazards in the game world.",
     response='Gameplay Mechanic'
 ),
 Prediction(
     reasoning='Laura\'s exclamation of "Oh no!" is a reactive response to an in-game event, likely tied to the trap mechanics described in the context. It signals a consequence of the previous actions (e.g., triggering the gas trap or failing a roll), which is central to the gameplay dynamics.',
     response='Gameplay Mechanic'
 ),
 Prediction(
     reasoning="Matt's question is a classic DM prompt anticipating challenges or consequences within the game's mechanics, such as trap difficulties or navigational hazards. This directly relates to gameplay mechanics like trap rolls, environmental challenges, or procedural outcomes.",
     response='Gameplay Mechanic'
 ),
 Prediction(
     reasoning='Liam\'s statement introduces a new environmental hazard ("gas trapped under a mound of shit") as part of the game world\'s challenges. This is a descriptive element of the setting rather than a mechanical rule, strategy, or out-of-game discussion. It contributes to the narrative and situational context for the players.',
     response='Worldbuilding'
 ),
 Prediction(
     reasoning="The conversation revolves around the game's environment, specifically a gas trap mentioned by Liam. Sam's question seeks clarification about the presence of gas, which is part of the world's hazards and setting. This dialogue is about the game's environment and its challenges, not mechanics, strategies, or out-of-game topics.",
     response='Worldbuilding'
 ),
 Prediction(
     reasoning="Laura's response provides additional detail about the environment, explaining that the gas has a smell reminiscent of Grog, which is a reference to a known character in the D&D universe. This enriches the setting and adds depth to the scenario, fitting within worldbuilding.",
     response='Worldbuilding'
 ),
 Prediction(
     reasoning='Liam\'s statement involves coordinating team movement and assigning specific roles (e.g., "bring up the rear," "bring the bear") to navigate a hazardous situation. This reflects in-game strategic planning to manage risks posed by the trapped gas, aligning with tactical decision-making during gameplay.',
     response='Strategising'
 ),
 Prediction(
     reasoning="Travis's question is about the method of marking traps during gameplay, which relates to how the group will strategize and coordinate actions to identify and avoid dangers. This is a tactical inquiry within the game's context, focusing on planning and execution.",
     response='Strategising'
 ),
 Prediction(
     reasoning="Liam's response explains the method used to mark traps (chalk) and his current positioning relative to another trap. This directly relates to in-game mechanics for handling traps, which is a core aspect of gameplay strategy and rule application.",
     response='Gameplay Mechanic'
 ),
 Prediction(
     reasoning='Travis is raising a strategic concern about the efficiency of their trap-marking method and the potential challenges of escaping quickly when encountering multiple traps. This involves evaluating their approach to navigation and risk management in the dungeon environment.',
     response='Strategising'
 ),
 Prediction(
     reasoning="The conversation revolves around navigating traps and planning an escape route, which involves strategizing in-game decisions about movement and risk management. Sam's question directly relates to the tactical consideration of retracing steps through dangerous terrain, aligning with strategic planning during gameplay.",
     response='Strategising'
 ),
 Prediction(
     reasoning='Travis\'s response "In a hurry" directly relates to the group\'s ongoing discussion about their situation—specifically, the implications of the chalk marks and the need for a quick escape. This is a continuation of strategizing their next moves in the game world.',
     response='Strategising'
 ),
 Prediction(
     reasoning="The dialogue involves the group discussing their situation and potential escape routes, which is part of planning and decision-making during gameplay. Taliesin's response is a brief acknowledgment of the need to remember their plan, indicating strategic thinking.",
     response='Strategising'
 ),
 Prediction(
     reasoning='The current turn is Travis\'s brief acknowledgment ("Oh yeah") following a discussion about their group\'s plan to return the way they came. This is a simple in-game dialogue response that does not introduce new worldbuilding, strategizing, or out-of-game conversation. It reflects a character\'s agreement or affirmation within the narrative context of the game.',
     response='Gameplay Mechanic'
 ),
 Prediction(
     reasoning="The dialogue reflects the characters' attitudes toward their current situation, contributing to the narrative context of the game world. It does not involve gameplay mechanics, strategic planning, or out-of-game discussion, but rather enhances the in-game atmosphere and character dynamics.",
     response='Worldbuilding'
 ),
 Prediction(
     reasoning='The dialogue involves the group deciding the order of actions, specifically assigning Trinket to take their turn first. This pertains to the sequence of actions within the game, which is a core aspect of gameplay mechanics. The mention of "run" likely refers to a character\'s turn in the game\'s action sequence, aligning with the rules and structure of the game.',
     response='Gameplay Mechanic'
 ),
 Prediction(
     reasoning="Liam's statement involves suggesting the use of an item from the bag to address the current challenge, which is an in-game action related to overcoming a hurdle. This directly pertains to the gameplay mechanics of using items or abilities during the adventure.",
     response='Gameplay Mechanic'
 ),
 Prediction(
     reasoning="MATT's response explains the specific mechanics for resolving Trinket's action, including the type of check (Dexterity) and the advantage granted by the party's aid. This directly relates to the rules and mechanics of the game, instructing players on how to resolve the action through dice rolls and game-specific parameters.",
     response='Gameplay Mechanic'
 ),
 Prediction(
     reasoning='LAURA\'s response is a reaction to the dexterity check result (an "eight") mentioned in the context. She is commenting on the outcome of a dice roll, which is directly tied to the gameplay mechanics of the session. This is a direct interaction with the game\'s mechanics rather than worldbuilding, strategy, or out-of-game discussion.',
     response='Gameplay Mechanic'
 ),
 Prediction(
     reasoning='The response "Eight? Okay." is Matt acknowledging the result of a dexterity check roll (Laura\'s roll of 8) for Trinket. This is a direct gameplay mechanic interaction where the DM (Matt) confirms the outcome of a skill check, which is part of resolving the scenario\'s challenge.',
     response='Gameplay Mechanic'
 ),
 Prediction(
     reasoning='Liam\'s question "Plus anything?" is asking if there are additional modifiers or bonuses to apply to the Dexterity check Trinket is making. This pertains to the rules and mechanics of ability checks in D&D, specifically whether any extra factors (like environmental effects, equipment, or situational bonuses) should influence the roll. This is a direct inquiry about gameplay mechanics.',
     response='Gameplay Mechanic'
 ),
 Prediction(
     reasoning='The dialogue involves players discussing the outcome of a game action (likely a dice roll or numerical result). Laura\'s "Nope!" confirms there are no additional modifiers or adjustments to the base number "Eight," which is a direct interaction about the game\'s mechanics.',
     response='Gameplay Mechanic'
 ),
 Prediction(
     reasoning="The dialogue involves players discussing the outcome of a dice roll (eight) and whether it applies to a character or item (Trinket). This is a direct interaction about the mechanics of resolving an action within the game, confirming the result's application.",
     response='Gameplay Mechanic'
 )]

### Evaluation

In [20]:
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score

def confusion_matrix_table(true_categories, predicted_categories, trace=None):
  for i in range(len(true_categories)):
    return confusion_matrix(true_categories, predicted_categories)

def cohens_kappa(true_categories, predicted_categories, trace=None):
  for i in range(len(true_categories)):
    return cohen_kappa_score(true_categories, predicted_categories)

def f1(true_categories, predicted_categories, trace=None):
  for i in range(len(true_categories)):
    return f1_score(true_categories, predicted_categories, average='weighted')

In [ ]:
# cohens_kappa(true_categories, predicted_categories)

In [ ]:
# confusion_matrix_table(true_categories, predicted_categories)

In [ ]:
# f1(true_categories, predicted_categories)

In [21]:
semanticF1 = dspy.evaluate.SemanticF1(threshold=0.66, decompositional=False)

In [22]:
evaluate = dspy.Evaluate(devset=trainset[0:50], metric = semanticF1, num_threads=1, provide_traceback=True)

In [23]:
trainset[0].response

'Worldbuilding'

In [24]:
evaluate(classify)

2026/07/13 14:18:29 INFO dspy.evaluate.evaluate: Average Metric: 31.0 / 50 (62.0%)

EvaluationResult(score=62.0, results=<list of 50 results>)

In [25]:
optimizer_copro = dspy.COPRO(metric=semanticF1, breadth=10, depth=3, init_temperature=1.4, track_stats=True)
optimizer_fewshot = dspy.BootstrapFewShot(metric=semanticF1, metric_threshold=0.66, teacher_settings=None, max_bootstrapped_demos=4, max_labeled_demos=16, max_rounds=1)
optimizer_mipro = dspy.MIPROv2(metric=semanticF1, auto='light')

In [26]:
!pip install dspy[optuna]

Requirement already satisfied: dspy[optuna] in /usr/local/lib/python3.12/dist-packages (3.2.1)
Requirement already satisfied: openai>=0.28.1 in /usr/local/lib/python3.12/dist-packages (from dspy[optuna]) (2.43.0)
Requirement already satisfied: regex>=2023.10.3 in /usr/local/lib/python3.12/dist-packages (from dspy[optuna]) (2025.11.3)
Requirement already satisfied: orjson>=3.9.0 in /usr/local/lib/python3.12/dist-packages (from dspy[optuna]) (3.11.9)
Requirement already satisfied: tqdm>=4.66.1 in /usr/local/lib/python3.12/dist-packages (from dspy[optuna]) (4.67.3)
Requirement already satisfied: requests>=2.31.0 in /usr/local/lib/python3.12/dist-packages (from dspy[optuna]) (2.32.4)
Requirement already satisfied: pydantic>=2.0 in /usr/local/lib/python3.12/dist-packages (from dspy[optuna]) (2.13.4)
Requirement already satisfied: litellm>=1.64.0 in /usr/local/lib/python3.12/dist-packages (from dspy[optuna]) (1.92.0)
Requirement already satisfied: diskcache>=5.6.0 in /usr/local/lib/python3.12/dist-packages (from dspy[optuna]) (5.6.3)
Requirement already satisfied: json-repair>=0.54.2 in /usr/local/lib/python3.12/dist-packages (from dspy[optuna]) (0.61.4)
Requirement already satisfied: tenacity>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from dspy[optuna]) (9.1.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from dspy[optuna]) (4.14.0)
Requirement already satisfied: asyncer==0.0.8 in /usr/local/lib/python3.12/dist-packages (from dspy[optuna]) (0.0.8)
Requirement already satisfied: cachetools>=5.5.0 in /usr/local/lib/python3.12/dist-packages (from dspy[optuna]) (6.2.6)
Requirement already satisfied: cloudpickle>=3.1.2 in /usr/local/lib/python3.12/dist-packages (from dspy[optuna]) (3.1.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from dspy[optuna]) (2.0.2)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from dspy[optuna]) (3.7.1)
Requirement already satisfied: gepa==0.0.27 in /usr/local/lib/python3.12/dist-packages (from gepa[dspy]==0.0.27->dspy[optuna]) (0.0.27)
Requirement already satisfied: typeguard==4.4.3 in /usr/local/lib/python3.12/dist-packages (from dspy[optuna]) (4.4.3)
Collecting optuna>=3.4.0 (from dspy[optuna])
  Downloading optuna-4.9.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: typing_extensions>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from typeguard==4.4.3->dspy[optuna]) (4.15.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio->dspy[optuna]) (3.18)
Requirement already satisfied: fastuuid<1.0,>=0.14.0 in /usr/local/lib/python3.12/dist-packages (from litellm>=1.64.0->dspy[optuna]) (0.14.0)
Requirement already satisfied: httpx<1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from litellm>=1.64.0->dspy[optuna]) (0.28.1)
Requirement already satisfied: python-dotenv<2.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from litellm>=1.64.0->dspy[optuna]) (1.2.2)
Requirement already satisfied: tiktoken<1.0,>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from litellm>=1.64.0->dspy[optuna]) (0.13.0)
Requirement already satisfied: importlib-metadata<9.0,>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from litellm>=1.64.0->dspy[optuna]) (8.9.0)
Requirement already satisfied: tokenizers<1.0,>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from litellm>=1.64.0->dspy[optuna]) (0.22.2)
Requirement already satisfied: click<9.0,>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from litellm>=1.64.0->dspy[optuna]) (8.4.2)
Requirement already satisfied: jinja2<4.0,>=3.1.6 in /usr/local/lib/python3.12/dist-packages (from litellm>=1.64.0->dspy[optuna]) (3.1.6)
Requirement already satisfied: aiohttp<4.0,>=3.10 in /usr/local/lib/python3.12/dist-packages (from litellm>=1.64.0->dspy[optuna]) (3.14.1)
Requirement already satisfied: jsonschema<5.0,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from litellm>=1.64.0->dspy[optuna]) (4.26.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai>=0.28.1->dspy[optuna]) (1.9.0)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai>=0.28.1->dspy[optuna]) (0.15.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai>=0.28.1->dspy[optuna]) (1.3.1)
Collecting alembic>=1.5.0 (from optuna>=3.4.0->dspy[optuna])
  Downloading alembic-1.18.5-py3-none-any.whl.metadata (7.2 kB)
Collecting colorlog (from optuna>=3.4.0->dspy[optuna])
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna>=3.4.0->dspy[optuna]) (26.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna>=3.4.0->dspy[optuna]) (2.0.51)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna>=3.4.0->dspy[optuna]) (6.0.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->dspy[optuna]) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->dspy[optuna]) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->dspy[optuna]) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31.0->dspy[optuna]) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31.0->dspy[optuna]) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31.0->dspy[optuna]) (2026.6.17)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0,>=3.10->litellm>=1.64.0->dspy[optuna]) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0,>=3.10->litellm>=1.64.0->dspy[optuna]) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0,>=3.10->litellm>=1.64.0->dspy[optuna]) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0,>=3.10->litellm>=1.64.0->dspy[optuna]) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0,>=3.10->litellm>=1.64.0->dspy[optuna]) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0,>=3.10->litellm>=1.64.0->dspy[optuna]) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0,>=3.10->litellm>=1.64.0->dspy[optuna]) (1.24.2)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna>=3.4.0->dspy[optuna]) (1.1.3)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0,>=0.28.0->litellm>=1.64.0->dspy[optuna]) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0,>=0.28.0->litellm>=1.64.0->dspy[optuna]) (0.16.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata<9.0,>=8.0.0->litellm>=1.64.0->dspy[optuna]) (4.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<4.0,>=3.1.6->litellm>=1.64.0->dspy[optuna]) (3.0.3)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema<5.0,>=4.0.0->litellm>=1.64.0->dspy[optuna]) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema<5.0,>=4.0.0->litellm>=1.64.0->dspy[optuna]) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema<5.0,>=4.0.0->litellm>=1.64.0->dspy[optuna]) (2026.5.1)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna>=3.4.0->dspy[optuna]) (3.5.2)
Requirement already satisfied: huggingface-hub<2.0,>=0.16.4 in /usr/local/lib/python3.12/dist-packages (from tokenizers<1.0,>=0.21.0->litellm>=1.64.0->dspy[optuna]) (1.20.1)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers<1.0,>=0.21.0->litellm>=1.64.0->dspy[optuna]) (3.29.4)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers<1.0,>=0.21.0->litellm>=1.64.0->dspy[optuna]) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers<1.0,>=0.21.0->litellm>=1.64.0->dspy[optuna]) (1.5.1)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers<1.0,>=0.21.0->litellm>=1.64.0->dspy[optuna]) (0.25.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.16.4->tokenizers<1.0,>=0.21.0->litellm>=1.64.0->dspy[optuna]) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.16.4->tokenizers<1.0,>=0.21.0->litellm>=1.64.0->dspy[optuna]) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.16.4->tokenizers<1.0,>=0.21.0->litellm>=1.64.0->dspy[optuna]) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.16.4->tokenizers<1.0,>=0.21.0->litellm>=1.64.0->dspy[optuna]) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.16.4->tokenizers<1.0,>=0.21.0->litellm>=1.64.0->dspy[optuna]) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.16.4->tokenizers<1.0,>=0.21.0->litellm>=1.64.0->dspy[optuna]) (0.1.2)
Downloading optuna-4.9.0-py3-none-any.whl (425 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 425.6/425.6 kB 8.3 MB/s eta 0:00:00
Downloading alembic-1.18.5-py3-none-any.whl (264 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 264.7/264.7 kB 26.1 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, alembic, optuna
Successfully installed alembic-1.18.5 colorlog-6.10.1 optuna-4.9.0

In [27]:
import litellm

In [28]:
litellm.drop_params=True

In [29]:
optimized_classifier = optimizer_fewshot.compile(classify, trainset=trainset[51:101])

 12%|█▏        | 6/50 [04:00<29:26, 40.14s/it]

Bootstrapped 4 full traces after 6 examples for up to 1 rounds, amounting to 6 attempts.

In [30]:
evaluate(optimized_classifier)

2026/07/13 14:46:00 INFO dspy.evaluate.evaluate: Average Metric: 37.0 / 50 (74.0%)

EvaluationResult(score=74.0, results=<list of 50 results>)

In [ ]:
# optimized_classifier.save("optimized_classifier.json")